/**
 * What can be counted about each surah, baked in at build time.
 *
 * Where it stands in the order of revelation, how long it is, which pages and
 * juz' of the muṣḥaf it runs through, where its prostrations fall, and the
 * letters it opens with if it opens with letters. These are the numbers at the
 * head of a surah's introduction, and they are counted from the corpus rather
 * than typed.
 *
 * `revealed` is the corpus's own figure: the order printed at the head of
 * each surah in the Egyptian muṣḥaf of 1924, which rests on the lists
 * transmitted from Ibn ʿAbbās and Jābir ibn Zayd. It places a surah by where it
 * began; many came down in parts, over years.
 *
 * `words` counts the words of the Uthmānī text, 77,433 in all.
 *
 * Generated by scripts/generate-surah-facts.mjs — run `npm run gen:facts`.
 */

export interface SurahFacts {
  /** Its place in the traditional order of revelation, 1 to 114. */
  revealed: number;
  place: "makkah" | "madinah";
  ayat: number;
  words: number;
  /** The first and last page it is on, in the Madīnah muṣḥaf. */
  pages: [number, number];
  /** The first and last juz' it runs through. */
  juz: [number, number];
  /** How many of the muṣḥaf's own paragraphs — rukūʿ — it is divided into. */
  ruku: number;
  /** The ayat of prostration in it. */
  sajdah: number[];
  /** The letters it opens with, or nothing. */
  letters: string;
  /** Whether the basmalah is written at its head. Only at-Tawbah has none. */
  basmalah: boolean;
}

export const SURAH_FACTS: SurahFacts[] = [
  { revealed: 5, place: "makkah", ayat: 7, words: 29, pages: [1, 1], juz: [1, 1], ruku: 1, sajdah: [], letters: "", basmalah: false },
  { revealed: 87, place: "madinah", ayat: 286, words: 6117, pages: [2, 49], juz: [1, 3], ruku: 40, sajdah: [], letters: "الٓمٓ", basmalah: true },
  { revealed: 89, place: "madinah", ayat: 200, words: 3481, pages: [50, 76], juz: [3, 4], ruku: 20, sajdah: [], letters: "الٓمٓ", basmalah: true },
  { revealed: 92, place: "madinah", ayat: 176, words: 3747, pages: [77, 106], juz: [4, 6], ruku: 24, sajdah: [], letters: "", basmalah: true },
  { revealed: 112, place: "madinah", ayat: 120, words: 2804, pages: [106, 127], juz: [6, 7], ruku: 16, sajdah: [], letters: "", basmalah: true },
  { revealed: 55, place: "makkah", ayat: 165, words: 3050, pages: [128, 150], juz: [7, 8], ruku: 20, sajdah: [], letters: "", basmalah: true },
  { revealed: 39, place: "makkah", ayat: 206, words: 3320, pages: [151, 176], juz: [8, 9], ruku: 24, sajdah: [206], letters: "الٓمٓصٓ", basmalah: true },
  { revealed: 88, place: "madinah", ayat: 75, words: 1234, pages: [177, 186], juz: [9, 10], ruku: 10, sajdah: [], letters: "", basmalah: true },
  { revealed: 113, place: "madinah", ayat: 129, words: 2498, pages: [187, 207], juz: [10, 11], ruku: 16, sajdah: [], letters: "", basmalah: false },
  { revealed: 51, place: "makkah", ayat: 109, words: 1833, pages: [208, 221], juz: [11, 11], ruku: 11, sajdah: [], letters: "الٓر", basmalah: true },
  { revealed: 52, place: "makkah", ayat: 123, words: 1917, pages: [221, 235], juz: [11, 12], ruku: 10, sajdah: [], letters: "الٓر", basmalah: true },
  { revealed: 53, place: "makkah", ayat: 111, words: 1777, pages: [235, 248], juz: [12, 13], ruku: 12, sajdah: [], letters: "الٓر", basmalah: true },
  { revealed: 96, place: "madinah", ayat: 43, words: 854, pages: [249, 255], juz: [13, 13], ruku: 6, sajdah: [15], letters: "الٓمٓر", basmalah: true },
  { revealed: 72, place: "makkah", ayat: 52, words: 830, pages: [255, 261], juz: [13, 13], ruku: 7, sajdah: [], letters: "الٓر", basmalah: true },
  { revealed: 54, place: "makkah", ayat: 99, words: 655, pages: [262, 267], juz: [14, 14], ruku: 6, sajdah: [], letters: "الٓر", basmalah: true },
  { revealed: 70, place: "makkah", ayat: 128, words: 1844, pages: [267, 281], juz: [14, 14], ruku: 16, sajdah: [50], letters: "", basmalah: true },
  { revealed: 50, place: "makkah", ayat: 111, words: 1556, pages: [282, 293], juz: [15, 15], ruku: 12, sajdah: [109], letters: "", basmalah: true },
  { revealed: 69, place: "makkah", ayat: 110, words: 1579, pages: [293, 304], juz: [15, 16], ruku: 12, sajdah: [], letters: "", basmalah: true },
  { revealed: 44, place: "makkah", ayat: 98, words: 961, pages: [305, 312], juz: [16, 16], ruku: 6, sajdah: [58], letters: "كٓهيعٓصٓ", basmalah: true },
  { revealed: 45, place: "makkah", ayat: 135, words: 1335, pages: [312, 321], juz: [16, 16], ruku: 8, sajdah: [], letters: "طه", basmalah: true },
  { revealed: 73, place: "makkah", ayat: 112, words: 1169, pages: [322, 331], juz: [17, 17], ruku: 7, sajdah: [], letters: "", basmalah: true },
  { revealed: 103, place: "madinah", ayat: 78, words: 1274, pages: [332, 341], juz: [17, 17], ruku: 10, sajdah: [18], letters: "", basmalah: true },
  { revealed: 74, place: "makkah", ayat: 118, words: 1050, pages: [342, 349], juz: [18, 18], ruku: 6, sajdah: [], letters: "", basmalah: true },
  { revealed: 102, place: "madinah", ayat: 64, words: 1316, pages: [350, 359], juz: [18, 18], ruku: 9, sajdah: [], letters: "", basmalah: true },
  { revealed: 42, place: "makkah", ayat: 77, words: 893, pages: [359, 366], juz: [18, 19], ruku: 6, sajdah: [60], letters: "", basmalah: true },
  { revealed: 47, place: "makkah", ayat: 227, words: 1318, pages: [367, 376], juz: [19, 19], ruku: 11, sajdah: [], letters: "طسٓمٓ", basmalah: true },
  { revealed: 48, place: "makkah", ayat: 93, words: 1151, pages: [377, 385], juz: [19, 20], ruku: 7, sajdah: [26], letters: "طسٓ", basmalah: true },
  { revealed: 49, place: "makkah", ayat: 88, words: 1430, pages: [385, 396], juz: [20, 20], ruku: 9, sajdah: [], letters: "طسٓمٓ", basmalah: true },
  { revealed: 85, place: "makkah", ayat: 69, words: 976, pages: [396, 404], juz: [20, 21], ruku: 7, sajdah: [], letters: "الٓمٓ", basmalah: true },
  { revealed: 84, place: "makkah", ayat: 60, words: 817, pages: [404, 410], juz: [21, 21], ruku: 6, sajdah: [], letters: "الٓمٓ", basmalah: true },
  { revealed: 57, place: "makkah", ayat: 34, words: 546, pages: [411, 414], juz: [21, 21], ruku: 4, sajdah: [], letters: "الٓمٓ", basmalah: true },
  { revealed: 75, place: "makkah", ayat: 30, words: 372, pages: [415, 417], juz: [21, 21], ruku: 3, sajdah: [15], letters: "الٓمٓ", basmalah: true },
  { revealed: 90, place: "madinah", ayat: 73, words: 1287, pages: [418, 427], juz: [21, 22], ruku: 9, sajdah: [], letters: "", basmalah: true },
  { revealed: 58, place: "makkah", ayat: 54, words: 883, pages: [428, 434], juz: [22, 22], ruku: 6, sajdah: [], letters: "", basmalah: true },
  { revealed: 43, place: "makkah", ayat: 45, words: 775, pages: [434, 440], juz: [22, 22], ruku: 5, sajdah: [], letters: "", basmalah: true },
  { revealed: 41, place: "makkah", ayat: 83, words: 725, pages: [440, 445], juz: [22, 23], ruku: 5, sajdah: [], letters: "يسٓ", basmalah: true },
  { revealed: 56, place: "makkah", ayat: 182, words: 861, pages: [446, 452], juz: [23, 23], ruku: 5, sajdah: [], letters: "", basmalah: true },
  { revealed: 38, place: "makkah", ayat: 88, words: 733, pages: [453, 458], juz: [23, 23], ruku: 5, sajdah: [24], letters: "صٓ", basmalah: true },
  { revealed: 59, place: "makkah", ayat: 75, words: 1172, pages: [458, 467], juz: [23, 24], ruku: 8, sajdah: [], letters: "", basmalah: true },
  { revealed: 60, place: "makkah", ayat: 85, words: 1219, pages: [467, 476], juz: [24, 24], ruku: 9, sajdah: [], letters: "حمٓ", basmalah: true },
  { revealed: 61, place: "makkah", ayat: 54, words: 794, pages: [477, 482], juz: [24, 25], ruku: 6, sajdah: [38], letters: "حمٓ", basmalah: true },
  { revealed: 62, place: "makkah", ayat: 53, words: 860, pages: [483, 489], juz: [25, 25], ruku: 5, sajdah: [], letters: "حمٓ عٓسٓقٓ", basmalah: true },
  { revealed: 63, place: "makkah", ayat: 89, words: 830, pages: [489, 495], juz: [25, 25], ruku: 7, sajdah: [], letters: "حمٓ", basmalah: true },
  { revealed: 64, place: "makkah", ayat: 59, words: 346, pages: [496, 498], juz: [25, 25], ruku: 3, sajdah: [], letters: "حمٓ", basmalah: true },
  { revealed: 65, place: "makkah", ayat: 37, words: 488, pages: [499, 502], juz: [25, 25], ruku: 4, sajdah: [], letters: "حمٓ", basmalah: true },
  { revealed: 66, place: "makkah", ayat: 35, words: 643, pages: [502, 506], juz: [26, 26], ruku: 4, sajdah: [], letters: "حمٓ", basmalah: true },
  { revealed: 95, place: "madinah", ayat: 38, words: 539, pages: [507, 510], juz: [26, 26], ruku: 4, sajdah: [], letters: "", basmalah: true },
  { revealed: 111, place: "madinah", ayat: 29, words: 560, pages: [511, 515], juz: [26, 26], ruku: 4, sajdah: [], letters: "", basmalah: true },
  { revealed: 106, place: "madinah", ayat: 18, words: 347, pages: [515, 517], juz: [26, 26], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 34, place: "makkah", ayat: 45, words: 373, pages: [518, 520], juz: [26, 26], ruku: 3, sajdah: [], letters: "قٓ", basmalah: true },
  { revealed: 67, place: "makkah", ayat: 60, words: 360, pages: [520, 523], juz: [26, 27], ruku: 3, sajdah: [], letters: "", basmalah: true },
  { revealed: 76, place: "makkah", ayat: 49, words: 312, pages: [523, 525], juz: [27, 27], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 23, place: "makkah", ayat: 62, words: 360, pages: [526, 528], juz: [27, 27], ruku: 3, sajdah: [62], letters: "", basmalah: true },
  { revealed: 37, place: "makkah", ayat: 55, words: 342, pages: [528, 531], juz: [27, 27], ruku: 3, sajdah: [], letters: "", basmalah: true },
  { revealed: 97, place: "madinah", ayat: 78, words: 351, pages: [531, 534], juz: [27, 27], ruku: 3, sajdah: [], letters: "", basmalah: true },
  { revealed: 46, place: "makkah", ayat: 96, words: 379, pages: [534, 537], juz: [27, 27], ruku: 3, sajdah: [], letters: "", basmalah: true },
  { revealed: 94, place: "madinah", ayat: 29, words: 574, pages: [537, 541], juz: [27, 27], ruku: 4, sajdah: [], letters: "", basmalah: true },
  { revealed: 105, place: "madinah", ayat: 22, words: 472, pages: [542, 545], juz: [28, 28], ruku: 3, sajdah: [], letters: "", basmalah: true },
  { revealed: 101, place: "madinah", ayat: 24, words: 445, pages: [545, 548], juz: [28, 28], ruku: 3, sajdah: [], letters: "", basmalah: true },
  { revealed: 91, place: "madinah", ayat: 13, words: 348, pages: [549, 551], juz: [28, 28], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 109, place: "madinah", ayat: 14, words: 221, pages: [551, 552], juz: [28, 28], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 110, place: "madinah", ayat: 11, words: 175, pages: [553, 554], juz: [28, 28], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 104, place: "madinah", ayat: 11, words: 180, pages: [554, 555], juz: [28, 28], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 108, place: "madinah", ayat: 18, words: 241, pages: [556, 557], juz: [28, 28], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 99, place: "madinah", ayat: 12, words: 287, pages: [558, 559], juz: [28, 28], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 107, place: "madinah", ayat: 12, words: 249, pages: [560, 561], juz: [28, 28], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 77, place: "makkah", ayat: 30, words: 333, pages: [562, 564], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 2, place: "makkah", ayat: 52, words: 300, pages: [564, 566], juz: [29, 29], ruku: 2, sajdah: [], letters: "نٓ", basmalah: true },
  { revealed: 78, place: "makkah", ayat: 52, words: 258, pages: [566, 568], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 79, place: "makkah", ayat: 44, words: 217, pages: [568, 570], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 71, place: "makkah", ayat: 28, words: 226, pages: [570, 571], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 40, place: "makkah", ayat: 28, words: 285, pages: [572, 573], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 3, place: "makkah", ayat: 20, words: 199, pages: [574, 575], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 4, place: "makkah", ayat: 56, words: 255, pages: [575, 577], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 31, place: "makkah", ayat: 40, words: 164, pages: [577, 578], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 98, place: "madinah", ayat: 31, words: 243, pages: [578, 580], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 33, place: "makkah", ayat: 50, words: 181, pages: [580, 581], juz: [29, 29], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 80, place: "makkah", ayat: 40, words: 173, pages: [582, 583], juz: [30, 30], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 81, place: "makkah", ayat: 46, words: 179, pages: [583, 584], juz: [30, 30], ruku: 2, sajdah: [], letters: "", basmalah: true },
  { revealed: 24, place: "makkah", ayat: 42, words: 133, pages: [585, 585], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 7, place: "makkah", ayat: 29, words: 104, pages: [586, 586], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 82, place: "makkah", ayat: 19, words: 80, pages: [587, 587], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 86, place: "makkah", ayat: 36, words: 169, pages: [587, 589], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 83, place: "makkah", ayat: 25, words: 107, pages: [589, 589], juz: [30, 30], ruku: 1, sajdah: [21], letters: "", basmalah: true },
  { revealed: 27, place: "makkah", ayat: 22, words: 109, pages: [590, 590], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 36, place: "makkah", ayat: 17, words: 61, pages: [591, 591], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 8, place: "makkah", ayat: 19, words: 72, pages: [591, 592], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 68, place: "makkah", ayat: 26, words: 92, pages: [592, 592], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 10, place: "makkah", ayat: 30, words: 137, pages: [593, 594], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 35, place: "makkah", ayat: 20, words: 82, pages: [594, 594], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 26, place: "makkah", ayat: 15, words: 54, pages: [595, 595], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 9, place: "makkah", ayat: 21, words: 71, pages: [595, 596], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 11, place: "makkah", ayat: 11, words: 40, pages: [596, 596], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 12, place: "makkah", ayat: 8, words: 27, pages: [596, 596], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 28, place: "makkah", ayat: 8, words: 34, pages: [597, 597], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 1, place: "makkah", ayat: 19, words: 72, pages: [597, 597], juz: [30, 30], ruku: 1, sajdah: [19], letters: "", basmalah: true },
  { revealed: 25, place: "makkah", ayat: 5, words: 30, pages: [598, 598], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 100, place: "madinah", ayat: 8, words: 94, pages: [598, 599], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 93, place: "madinah", ayat: 8, words: 36, pages: [599, 599], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 14, place: "makkah", ayat: 11, words: 40, pages: [599, 600], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 30, place: "makkah", ayat: 11, words: 36, pages: [600, 600], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 16, place: "makkah", ayat: 8, words: 28, pages: [600, 600], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 13, place: "makkah", ayat: 3, words: 14, pages: [601, 601], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 32, place: "makkah", ayat: 9, words: 33, pages: [601, 601], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 19, place: "makkah", ayat: 5, words: 23, pages: [601, 601], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 29, place: "makkah", ayat: 4, words: 17, pages: [602, 602], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 17, place: "makkah", ayat: 7, words: 25, pages: [602, 602], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 15, place: "makkah", ayat: 3, words: 10, pages: [602, 602], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 18, place: "makkah", ayat: 6, words: 26, pages: [603, 603], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 114, place: "madinah", ayat: 3, words: 19, pages: [603, 603], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 6, place: "makkah", ayat: 5, words: 23, pages: [603, 603], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 22, place: "makkah", ayat: 4, words: 15, pages: [604, 604], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 20, place: "makkah", ayat: 5, words: 23, pages: [604, 604], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
  { revealed: 21, place: "makkah", ayat: 6, words: 20, pages: [604, 604], juz: [30, 30], ruku: 1, sajdah: [], letters: "", basmalah: true },
];

/** The surah that stands at a given place in the order of revelation. */
const BY_REVELATION: number[] = [];
SURAH_FACTS.forEach((f, i) => (BY_REVELATION[f.revealed - 1] = i + 1));

/** Every surah, in the order they began to come down. */
export const REVELATION_ORDER: readonly number[] = BY_REVELATION;

/** How many surahs the traditional list places in Makkah, before the Hijrah. */
export const MAKKAN_COUNT = SURAH_FACTS.filter((f) => f.place === "makkah").length;
